steps:
- label: "Generate Short Sentence"
  plugins:
  - docker#v5.3.0:
      image: "python:3.13"
      command: [ "python", "-c", "import loremipsum; print(loremipsum.sentence(max_char=20), file=open('result.txt', 'w'))" ]
  artifact_paths:
  - "result.txt"

- label: "Annotate Sentence"
  command: "buildkite-agent annotate --style info \"$(cat result.txt)\""
  depends_on: "Generate Short Sentence"

- label: "Generate Paragraph"
  command: "python -c \"import loremipsum; print(loremipsum.paragraph(max_char=100))\" > paragraph.txt"
  plugins:
  - docker#v5.3.0:
      image: "python:3.13"
  depends_on: "Generate Short Sentence"

- label: "Annotate Paragraph"
  command: "buildkite-agent annotate --style success \"$(cat paragraph.txt)\""
  depends_on: "Generate Paragraph"
