steps:
- label: "Generate Short Sentence"
  key: 'abc'
  plugins:
  - docker#v5.3.0:
      image: "python:3.13"
      command: [ "python", "--version" ]

# - label: "Annotate Sentence"
#   command: "buildkite-agent annotate --style info \"$(cat result.txt)\""
#   depends_on: "abc"

# - label: "Generate Paragraph"
#   key: "def"
#   command: "python -c \"import loremipsum; print(loremipsum.paragraph(max_char=100))\" > paragraph.txt"
#   plugins:
#   - docker#v5.3.0:
#       image: "python:3.13"
#   depends_on: "abc"

# - label: "Annotate Paragraph"
#   command: "buildkite-agent annotate --style success \"$(cat paragraph.txt)\""
#   depends_on: "def"
